[[sources]] # list of sources to load
name = "friendly-snippets"  # optional name shown on snippet description
git = "https://github.com/rafamadriz/friendly-snippets.git" # git repo with snippets collections

[[sources.paths]] # list of paths to load on current source
scope = ["python"]  # optional scopes for current snippets
path = "snippets/python/python.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["rust"]  # optional scopes for current snippets
path = "snippets/rust/rust.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["rust"]  # optional scopes for current snippets
path = "snippets/rust/rustdoc.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["markdown", "text"]  # optional scopes for current snippets
path = "snippets/license.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["markdown"]  # optional scopes for current snippets
path = "snippets/markdown.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["git-commit"]  # optional scopes for current snippets
path = "snippets/gitcommit.json"  # where snippet file or dir located in repo

[[sources.paths]] # list of paths to load on current source
scope = ["text", "markdown", "git-commit", "rust"]  # optional scopes for current snippets
path = "snippets/loremipsum.json"  # where snippet file or dir located in repo
